title: Federico Damián Schonborn
baseURL: https://fdschonborn.github.io/
languageCode: en-us
theme: one
enableGitInfo: true
enableEmoji: true

params:
  title: "Federico's Hideout :crab:"

markup:
  highlight:
    lineNos: true
    style: solarized-dark
