title: Federico's Hideout
baseURL: https://fdschonborn.github.io/
languageCode: en-us
theme: one
enableGitInfo: true
enableEmoji: true

markup:
  highlight:
    lineNos: true
    style: solarized-dark
